site_name: Azure Firewall Egress Controller
repo_name: "Azure/azure-firewall-egress-controller"
repo_url: "https://github.com/Azure/azure-firewall-egress-controller"

theme:
  name: readthedocs
  highlightjs: true
  hljs_languages:
    - yaml
    - rust
    - bash
    - go
  shortcuts:
    help: 191    # ?
    next: 78     # n
    previous: 80 # p
    search: 83   # s

plugins:
  - search
  - awesome-pages:
      filename: .index
      collapse_single_pages: true

extra_css:
  - css/extra.css
