#nginx0-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx0-deployment
  labels:
    app: nginx0-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx0
  template:
    metadata:
      labels:
        app: nginx0
    spec:
      containers:
      - name: nginx
        image: navyaaksegress.azurecr.io/nginx:v1
        ports:
        - containerPort: 80
      nodeSelector: 
        app: testing
---
#testing.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: testing-app
  labels:
    app: testing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testing
  template:
    metadata:
      labels:
        app: testing
    spec:
      containers:
      - name: nginx
        image: navyaaksegress.azurecr.io/nginx:v1
        ports:
        - containerPort: 443
      nodeSelector:
        app: testing
