---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-egress-azure-firewall-egress-controller-io-v1-egressrules
  failurePolicy: Fail
  name: vegressrules.kb.io
  rules:
  - apiGroups:
    - egress.azure-firewall-egress-controller.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - egressrules
  sideEffects: None
