apiVersion: egress.azure-firewall-egress-controller.io/v1
kind: Egressrules
metadata:
  name: egressrules-sample2
spec:
  # TODO(user): Add fields here
  nodeSelector:
    - app: "temp"
  destinationAddresses: ["*"]
  protocol : ["HTTP:400"]
  targetFqdns : ["*"]
  targetUrls : []
  action : "Deny"
  ruleType: "Application"
