apiVersion: egress.azure-firewall-egress-controller.io/v1
kind: Egressrules
metadata:
  name: egressrules-sample3
spec:
  ruleCollectionName: "aks-fw-ng"
  nodeSelector:
    - app: "testing"
  targetFqdns: ["*.google.com"]
  protocol : ["HTTP:800"]
  action : "Allow"
  ruleType: "Application"
