apiVersion: egress.azure-firewall-egress-controller.io/v1
kind: Egressrules
metadata:
  name: egressrules-sample4
spec:
  # TODO(user): Add fields here
  ruleCollectionName: "testing-voting-app"
  nodeSelector:
    - app: "testing"
  destinationAddresses: ["*"]
  protocol : ["HTTP:400"]
  targetFqdns : ["*"]
  targetUrls : []
  action : "Deny"
  ruleType: "Application"
