apiVersion: egress.azure-firewall-egress-controller.io/v1
kind: Egressrules
metadata:
  name: egressrules-sample3
spec:
  nodeSelector:
    - app: "testing"
  rules:
    - ruleName: "erule3-rule"
      ruleCollectionName: "aks-fw-ng-allow"
      targetFqdns: ["*.google.com"]
      protocol : ["HTTP:800"]
      action : "Allow"
      ruleType: "Application"
