apiVersion: egress.tutorial.kubebuilder.io/v1
kind: Egressrules
metadata:
  name: egressrules-sample2
  namespace : default
spec:
  # TODO(user): Add fields here
  podSelector:
    - app: "temp"
  destinationAddresses: ["*"]
  protocol : ["HTTP:400"]
  targetFqdns : ["*"]
  targetUrls : []
  action : "Deny"
  ruleType: "Application"
