apiVersion: egress.tutorial.kubebuilder.io/v1
kind: Egressrules
metadata:
  name: egressrules-sample1
  namespace : default
spec:
  # TODO(user): Add fields here
  podSelector:
    - app: "nginx0"
  destinationFqdns: ["*"]
  destinationAddresses: []
  destinationPorts: ["*"]
  protocol : ["TCP","UDP"]
  action : "Deny"
  ruleType: "Network"


  
