apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: aks-egress-leader-election-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: aks-egress-leader-election-role
subjects:
- kind: ServiceAccount
  name: aks-egress-controller-manager
  namespace: aks-egress-system
