---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: aks-egress-validating-webhook-configuration
  labels:
    app.kubernetes.io/name: validatingwebhookconfiguration
    app.kubernetes.io/instance: validating-webhook-configuration
    app.kubernetes.io/component: webhook
    app.kubernetes.io/created-by: aks-egress
    app.kubernetes.io/part-of: aks-egress
    app.kubernetes.io/managed-by: kustomize
  annotations:
    cert-manager.io/inject-ca-from: aks-egress-system/aks-egress-serving-cert
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: aks-egress-webhook-service
      namespace: aks-egress-system
      path: /validate-egress-azure-firewall-egress-controller-io-v1-egressrules
  failurePolicy: Fail
  name: vegressrules.kb.io
  rules:
  - apiGroups:
    - egress.azure-firewall-egress-controller.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - egressrules
  sideEffects: None
