apiVersion: v1
kind: Secret
metadata:
  name: aks-egress-controller-secret
  namespace: aks-egress-system
type: Opaque
data:
  AZURE_TENANT_ID: {{ .Values.auth.tenantId | b64enc | quote }}
  AZURE_CLIENT_ID: {{ .Values.auth.clientId | b64enc | quote }}
  AZURE_CLIENT_SECRET: {{ .Values.auth.clientSecret | b64enc | quote }}