# permissions for end users to edit egressrules.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: egressrules-editor-role
rules:
- apiGroups:
  - egress.tutorial.kubebuilder.io
  resources:
  - egressrules
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - egress.tutorial.kubebuilder.io
  resources:
  - egressrules/status
  verbs:
  - get
