name: ci
on:
  push:
    branches:
      - master
      - main
      - samankal/*
    paths:
      - ".github/workflows/chart.yaml"
      - "charts/**"
      - "docs/**"

permissions:
  contents: write
jobs:
  deploy-helm:
      runs-on: ubuntu-20.04
      steps:
        - uses: actions/checkout@v3
          with:
            submodules: true
            fetch-depth: 0
        - name: Publish Helm chart
          uses: stefanprodan/helm-gh-pages@v1.7.0
          with:
            token: ${{ secrets.GITHUB_TOKEN }}
            charts_dir: charts
            target_dir: charts
            linting: off
  deploy-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
          submodules: true
          fetch-depth: 0
      - uses: actions/cache@v2
        with:
          key: ${{ github.ref }}
          path: .cache
      - name: Publish Helm chart
      uses: stefanprodan/helm-gh-pages@v1.7.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        charts_dir: charts
        target_dir: charts
        linting: off
      - run: pip install mkdocs-material
      - run: pip install mkdocs-awesome-pages-plugin
      - run: mkdocs gh-deploy --force
